name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install && build
        run: |
          npm install
          npm run build
          
      - name: Set SSH Environment
        env:
          KEY: ${{secrets.ID_RSA}}
          HOST: ${{secrets.HOST}}
        run: |
          mkdir -p ~/.ssh/
          echo "$KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "$HOST" > ~/.ssh/known_hosts
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
        
      - name: Scp
        run: |
          scp -r dist/* ${{secrets.ADDRES}}